-- WORLD LIFE EXPECTANCY DATA CLEANING PROJECT
-- OBJECTIVE: CLEAN AND UPDATE TABLE 
/*
----------------------------------------------------------------------------------------------------------------------------------------------- */
-- REMOVE DUPLICATES 

SELECT * FROM WLE;

SELECT COUNTRY,`YEAR`,CONCAT(COUNTRY,`YEAR`),COUNT(CONCAT(COUNTRY,`YEAR`))
FROM WLE
GROUP BY COUNTRY,`YEAR`,CONCAT(COUNTRY,`YEAR`)
HAVING COUNT(CONCAT(COUNTRY,`YEAR`)) > 1; -- DUPLICATES IDENTIFIED 

SELECT * FROM WLE;

SELECT * 
FROM(
SELECT ROW_ID,CONCAT(COUNTRY,YEAR),ROW_NUMBER() OVER(PARTITION BY CONCAT(COUNTRY,YEAR) ) AS DELETE_ROW FROM WLE) AS DELETE_TABLE
WHERE DELETE_ROW > 1;

DELETE FROM WLE
WHERE ROW_ID IN ( SELECT ROW_ID
FROM(
SELECT ROW_ID,CONCAT(COUNTRY,YEAR),ROW_NUMBER() OVER(PARTITION BY CONCAT(COUNTRY,YEAR) ) AS DELETE_ROW FROM WLE) AS DELETE_TABLE
WHERE DELETE_ROW > 1); -- DUPLICATES REMOVED FROM TABLE 

SELECT * FROM WLE;
/* 
---------------------------------------------------------------------------------------------------------------------------------------------------*/
-- POPULATE BLANK VALUES IN STATUS COLUMN 

SELECT * FROM WLE;

SELECT * FROM WLE 
WHERE `STATUS` = '';

-- USING SELF JOIN TO FILTER AND UPDATE THE SAME TABLE 
UPDATE WLE W1
JOIN WLE W2
ON W1.COUNTRY=W2.COUNTRY
SET W1.`STATUS` = 'DEVELOPING'
WHERE W1.`STATUS` = ''
AND W2.`STATUS` <> ''
AND W2.`STATUS` = 'DEVELOPING'; -- FILL VALUES THAT ARE BLANK IN W1.WLE AND FILTER USING DEVELOPING IN W2.WLE 

UPDATE WLE W1
JOIN WLE W2
ON W1.COUNTRY=W2.COUNTRY
SET W1.`STATUS` = 'Developed'
WHERE W1.`STATUS` = ''
AND W2.`STATUS` <> ''
AND W2.`STATUS` = 'Developed';

Select COUNT(`STATUS`) FROM WLE 
WHERE `STATUS` = ''; -- IDENTIFY IF THE STATUS COLUMN STILL HAS BLANKS REMAINING 

SELECT * FROM WLE ;

/*----------------------------------------------------------------------------------------------------------------------------------------------- */

-- FILL BLANK VALUES IN LIFE EXPECTANCY 

SELECT * FROM WLE ;

SELECT COUNT(`LIFE EXPECTANCY`) AS COUNT_BLANK_VALUES FROM WLE
WHERE `LIFE EXPECTANCY` = ''; -- IDENTIFY HOW MANY BLANK VALUES ARE IN THE COLUMN 
          

SELECT *
FROM WLE 
WHERE `LIFE EXPECTANCY` = ''; -- FIND ROWS THAT NEED TO BE UPDATED 

SELECT * FROM WLE 
WHERE COUNTRY = 'Afghanistan';

SELECT ROUND(((SELECT `LIFE EXPECTANCY` FROM WLE WHERE ROW_ID = 4 ) 
            + (SELECT `LIFE EXPECTANCY` FROM WLE WHERE ROW_ID = 6))/2,1) AS AVERAGE_BETWEEN_LIFE_EXPECTANCY_2019_2017
FROM WLE;-- FIND THE AVERAGE LIFE EXPECTANCY BETWEEN 2019 AND 2017 TO FIND THE VALUE FOR 2018

SELECT *,`LIFE EXPECTANCY` FROM WLE
WHERE COUNTRY = 'Afghanistan' AND `Life Expectancy` =''; -- FIND ROW_ID TO UPDATE ROW  

UPDATE WLE 
SET `LIFE EXPECTANCY` = (SELECT ROUND(((SELECT `LIFE EXPECTANCY` FROM WLE WHERE ROW_ID = 4 ) 
                      + (SELECT `LIFE EXPECTANCY` FROM WLE WHERE ROW_ID = 6))/2,1) AS AVERAGE_BETWEEN_LIFE_EXPECTANCY_2019_2017)
WHERE COUNTRY = 'Afghanistan' AND `LIFE EXPECTANCY` = '';-- NEED TO WRAP QUERY IN A JOIN FOR IT TO PROCESS, YOU CAN NOT UPDATE AND PULL FROM THE SAME TABLE IN THE SAME QUERY  

UPDATE WLE AS W1
JOIN (SELECT ROUND(((SELECT `LIFE EXPECTANCY` FROM WLE WHERE ROW_ID = 4 ) 
				 + (SELECT `LIFE EXPECTANCY` FROM WLE WHERE ROW_ID = 6))/2,1)  
                    AS FINAL_RESULT) AS W2
SET W1.`LIFE EXPECTANCY` = W2.FINAL_RESULT
WHERE COUNTRY = 'Afghanistan' AND `LIFE EXPECTANCY` = ''; -- TABLE UPDATED

SELECT * FROM WLE 
WHERE COUNTRY = 'ALBANIA'; -- ROW_ID 20 AND 22

SELECT ROUND(((SELECT `LIFE EXPECTANCY` FROM WLE WHERE ROW_ID = 20 ) 
            + (SELECT `LIFE EXPECTANCY` FROM WLE WHERE ROW_ID = 22))/2,1) 
FROM WLE; -- AVERAGE LIFE EXPECTANCY BETWEEN ROW_ID 20 AND 22

UPDATE WLE W1
JOIN (SELECT ROUND(((SELECT `LIFE EXPECTANCY` FROM WLE WHERE ROW_ID = 20 ) 
                  + (SELECT `LIFE EXPECTANCY` FROM WLE WHERE ROW_ID = 22))/2,1) 
                     AS FINAL_RESULT ) AS W2
SET W1.`LIFE EXPECTANCY` = W2.FINAL_RESULT
WHERE COUNTRY = 'Albania' AND `LIFE EXPECTANCY` = ''; -- table updated

SELECT * FROM WLE 
WHERE `LIFE EXPECTANCY` ='';-- ALL BLANK COLUMNS UPDATED

SELECT * FROM WLE